REP =-d ../classes
FILE =*.java
all: board character exception player tile game

# Compilation des différents package
board: 
	javac game/board/$(FILE) $(REP)

character: 
	javac game/character/$(FILE) $(REP)

exception:
	javac game/exception/$(FILE) $(REP)

player:
	javac game/player/$(FILE) $(REP)

tile:
	javac game/tile/$(FILE) $(REP)

game:
	javac game/$(FILE) $(REP)

# Compilation des différents test


